const actionsTypes = Object.freeze({
    GET_DATA: "GET_DATA",
    SET_COUNT: "SET_COUNT",
    PAGINATION_NEXT: "PAGINATION_NEXT",
    PAGINATION_PREV: "PAGINATION_PREV",
    BUILD_QUERY: "BUILD_QUERY",
    APPLY_FILTERS: "APPLY_FILTERS",
    CLEAR_FILTERS: "CLEAR_FILTERS",
    SET_ORDER: "SET_ORDER",
    SEARCH: "SEARCH",
    REMOVE_FROM_SEARCH: "REMOVE_FROM_SEARCH",
    UPDATE: "UPDATE",
    DOWNLOAD_RESULT:"DOWNLOAD_RESULT"

});

export default actionsTypes;